// TypeScript models auto-generated from OpenAPI schema
// Generated by: npx openapi-typescript http://localhost:5201/swagger/v1/swagger.json -o src/models/api.ts
// 
// Run this command after API schema changes to regenerate models
// The models will be automatically imported by the API client and views

export interface Feature {
  id?: string;
  name?: string;
  description?: string | null;
  createdAt?: string;
}

export interface User {
  id?: string;
  email?: string;
  displayName?: string | null;
  isActive?: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface ResponseDtoFeature {
  success?: boolean;
  status?: number;
  data?: Feature;
  message?: string | null;
  traceId?: string;
  meta?: Record<string, unknown> | null;
}

export interface ResponseDtoFeatureArray {
  success?: boolean;
  status?: number;
  data?: Feature[];
  message?: string | null;
  traceId?: string;
  meta?: Record<string, unknown> | null;
}

export interface ResponseDtoObject {
  success?: boolean;
  status?: number;
  data?: Record<string, unknown> | null;
  message?: string | null;
  traceId?: string;
  meta?: Record<string, unknown> | null;
}
